### ISSUE TITLE
[IDEA] Please add multiple tokens!

### ISSUE THREAD

**Issue by Crysiz2631** [xzerios/Discord-Auto-Advertiser#1]
Please add multiple tokens! it is very wanted, please add it like channels in config.json or new file called tokens.txt.

**Comment by xzerios** [comment]
Hi! I've already considered implementing multi-token support but I'm not sure how it should be done.
It'd be great if you could let me know!

**Comment by Crysiz2631** [comment]
i might have created it. contact me on discord Crys#0001

**Comment by xzerios** [comment]
Will work on it soon.

**Comment by xzerios** [comment]
Would require a full recode which I currently won't be doing for the time being.
